// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        *EventSource           `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // JSON-serialized event data
	Metadata      *EventMetadata         `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *EventEnvelope) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventEnvelope) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BranchId      string                 `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	WorkstationId string                 `protobuf:"bytes,4,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventSource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *EventSource) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventSource) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *EventSource) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventMetadata) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Discount      float64                `protobuf:"fixed64,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         float64                `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderItem) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrxNumber     string                 `protobuf:"bytes,2,opt,name=trx_number,json=trxNumber,proto3" json:"trx_number,omitempty"`
	CustomerId    *int64                 `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3,oneof" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,6,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	TaxAmount     float64                `protobuf:"fixed64,7,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	Discount      float64                `protobuf:"fixed64,8,opt,name=discount,proto3" json:"discount,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,10,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CashierId     int64                  `protobuf:"varint,12,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	ShiftId       int64                  `protobuf:"varint,13,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderCreatedEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCreatedEvent) GetTrxNumber() string {
	if x != nil {
		return x.TrxNumber
	}
	return ""
}

func (x *OrderCreatedEvent) GetCustomerId() int64 {
	if x != nil && x.CustomerId != nil {
		return *x.CustomerId
	}
	return 0
}

func (x *OrderCreatedEvent) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *OrderCreatedEvent) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreatedEvent) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *OrderCreatedEvent) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *OrderCreatedEvent) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderCreatedEvent) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderCreatedEvent) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderCreatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderCreatedEvent) GetCashierId() int64 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *OrderCreatedEvent) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

func (x *OrderCreatedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OrderCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrxNumber     string                 `protobuf:"bytes,2,opt,name=trx_number,json=trxNumber,proto3" json:"trx_number,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCompletedEvent) Reset() {
	*x = OrderCompletedEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedEvent) ProtoMessage() {}

func (x *OrderCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedEvent.ProtoReflect.Descriptor instead.
func (*OrderCompletedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCompletedEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCompletedEvent) GetTrxNumber() string {
	if x != nil {
		return x.TrxNumber
	}
	return ""
}

func (x *OrderCompletedEvent) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderCompletedEvent) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type OrderCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrxNumber     string                 `protobuf:"bytes,2,opt,name=trx_number,json=trxNumber,proto3" json:"trx_number,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledBy   int64                  `protobuf:"varint,4,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	CancelledAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelledEvent) Reset() {
	*x = OrderCancelledEvent{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledEvent) ProtoMessage() {}

func (x *OrderCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledEvent.ProtoReflect.Descriptor instead.
func (*OrderCancelledEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *OrderCancelledEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderCancelledEvent) GetTrxNumber() string {
	if x != nil {
		return x.TrxNumber
	}
	return ""
}

func (x *OrderCancelledEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderCancelledEvent) GetCancelledBy() int64 {
	if x != nil {
		return x.CancelledBy
	}
	return 0
}

func (x *OrderCancelledEvent) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

type CardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last4         string                 `protobuf:"bytes,1,opt,name=last4,proto3" json:"last4,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardData) Reset() {
	*x = CardData{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardData) ProtoMessage() {}

func (x *CardData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardData.ProtoReflect.Descriptor instead.
func (*CardData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *CardData) GetLast4() string {
	if x != nil {
		return x.Last4
	}
	return ""
}

func (x *CardData) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

type UPIData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Vpa           string                 `protobuf:"bytes,2,opt,name=vpa,proto3" json:"vpa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UPIData) Reset() {
	*x = UPIData{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UPIData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UPIData) ProtoMessage() {}

func (x *UPIData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UPIData.ProtoReflect.Descriptor instead.
func (*UPIData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *UPIData) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *UPIData) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

type PaymentProcessedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CardData      *CardData              `protobuf:"bytes,6,opt,name=card_data,json=cardData,proto3,oneof" json:"card_data,omitempty"`
	UpiData       *UPIData               `protobuf:"bytes,7,opt,name=upi_data,json=upiData,proto3,oneof" json:"upi_data,omitempty"`
	ProcessedBy   int64                  `protobuf:"varint,8,opt,name=processed_by,json=processedBy,proto3" json:"processed_by,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentProcessedEvent) Reset() {
	*x = PaymentProcessedEvent{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProcessedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProcessedEvent) ProtoMessage() {}

func (x *PaymentProcessedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProcessedEvent.ProtoReflect.Descriptor instead.
func (*PaymentProcessedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentProcessedEvent) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *PaymentProcessedEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentProcessedEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentProcessedEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentProcessedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentProcessedEvent) GetCardData() *CardData {
	if x != nil {
		return x.CardData
	}
	return nil
}

func (x *PaymentProcessedEvent) GetUpiData() *UPIData {
	if x != nil {
		return x.UpiData
	}
	return nil
}

func (x *PaymentProcessedEvent) GetProcessedBy() int64 {
	if x != nil {
		return x.ProcessedBy
	}
	return 0
}

func (x *PaymentProcessedEvent) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type RefundIssuedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      int64                  `protobuf:"varint,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	PaymentId     int64                  `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RefundedBy    int64                  `protobuf:"varint,5,opt,name=refunded_by,json=refundedBy,proto3" json:"refunded_by,omitempty"`
	RefundedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundIssuedEvent) Reset() {
	*x = RefundIssuedEvent{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundIssuedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundIssuedEvent) ProtoMessage() {}

func (x *RefundIssuedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundIssuedEvent.ProtoReflect.Descriptor instead.
func (*RefundIssuedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *RefundIssuedEvent) GetRefundId() int64 {
	if x != nil {
		return x.RefundId
	}
	return 0
}

func (x *RefundIssuedEvent) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RefundIssuedEvent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundIssuedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundIssuedEvent) GetRefundedBy() int64 {
	if x != nil {
		return x.RefundedBy
	}
	return 0
}

func (x *RefundIssuedEvent) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

type LowStockAlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	CurrentStock  int32                  `protobuf:"varint,4,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	BranchId      string                 `protobuf:"bytes,6,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LowStockAlertEvent) Reset() {
	*x = LowStockAlertEvent{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowStockAlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowStockAlertEvent) ProtoMessage() {}

func (x *LowStockAlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowStockAlertEvent.ProtoReflect.Descriptor instead.
func (*LowStockAlertEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *LowStockAlertEvent) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *LowStockAlertEvent) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *LowStockAlertEvent) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *LowStockAlertEvent) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

func (x *LowStockAlertEvent) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *LowStockAlertEvent) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

type StockUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	PreviousStock int32                  `protobuf:"varint,4,opt,name=previous_stock,json=previousStock,proto3" json:"previous_stock,omitempty"`
	NewStock      int32                  `protobuf:"varint,5,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	ChangeType    string                 `protobuf:"bytes,6,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // sale, restock, adjustment, transfer
	ChangeAmount  int32                  `protobuf:"varint,7,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedBy     int64                  `protobuf:"varint,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdatedEvent) Reset() {
	*x = StockUpdatedEvent{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdatedEvent) ProtoMessage() {}

func (x *StockUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdatedEvent.ProtoReflect.Descriptor instead.
func (*StockUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *StockUpdatedEvent) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StockUpdatedEvent) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StockUpdatedEvent) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockUpdatedEvent) GetPreviousStock() int32 {
	if x != nil {
		return x.PreviousStock
	}
	return 0
}

func (x *StockUpdatedEvent) GetNewStock() int32 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

func (x *StockUpdatedEvent) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *StockUpdatedEvent) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *StockUpdatedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StockUpdatedEvent) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *StockUpdatedEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AuditLogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	OldValues     []byte                 `protobuf:"bytes,6,opt,name=old_values,json=oldValues,proto3" json:"old_values,omitempty"` // JSON
	NewValues     []byte                 `protobuf:"bytes,7,opt,name=new_values,json=newValues,proto3" json:"new_values,omitempty"` // JSON
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEvent) Reset() {
	*x = AuditLogEvent{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEvent) ProtoMessage() {}

func (x *AuditLogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEvent.ProtoReflect.Descriptor instead.
func (*AuditLogEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *AuditLogEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditLogEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditLogEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuditLogEvent) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuditLogEvent) GetOldValues() []byte {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *AuditLogEvent) GetNewValues() []byte {
	if x != nil {
		return x.NewValues
	}
	return nil
}

func (x *AuditLogEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLogEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLogEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MetricsBatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkstationId string                 `protobuf:"bytes,1,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatchEvent) Reset() {
	*x = MetricsBatchEvent{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatchEvent) ProtoMessage() {}

func (x *MetricsBatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatchEvent.ProtoReflect.Descriptor instead.
func (*MetricsBatchEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *MetricsBatchEvent) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

func (x *MetricsBatchEvent) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsBatchEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricsBatchEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NotificationTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // all, branch, workstation, user
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTarget) Reset() {
	*x = NotificationTarget{}
	mi := &file_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTarget) ProtoMessage() {}

func (x *NotificationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTarget.ProtoReflect.Descriptor instead.
func (*NotificationTarget) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{15}
}

func (x *NotificationTarget) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationTarget) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type NotificationAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // open_url, navigate, refresh
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAction) Reset() {
	*x = NotificationAction{}
	mi := &file_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAction) ProtoMessage() {}

func (x *NotificationAction) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAction.ProtoReflect.Descriptor instead.
func (*NotificationAction) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{16}
}

func (x *NotificationAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationAction) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type NotificationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"` // low, normal, high, urgent
	Target         *NotificationTarget    `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Action         *NotificationAction    `protobuf:"bytes,6,opt,name=action,proto3,oneof" json:"action,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{17}
}

func (x *NotificationEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationEvent) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *NotificationEvent) GetTarget() *NotificationTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *NotificationEvent) GetAction() *NotificationAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *NotificationEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ServerHeartbeatEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ServerUrl      string                 `protobuf:"bytes,2,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // online, offline
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ActiveBranches int32                  `protobuf:"varint,5,opt,name=active_branches,json=activeBranches,proto3" json:"active_branches,omitempty"`
	ActiveUsers    int32                  `protobuf:"varint,6,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerHeartbeatEvent) Reset() {
	*x = ServerHeartbeatEvent{}
	mi := &file_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeatEvent) ProtoMessage() {}

func (x *ServerHeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeatEvent.ProtoReflect.Descriptor instead.
func (*ServerHeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{18}
}

func (x *ServerHeartbeatEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ServerHeartbeatEvent) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *ServerHeartbeatEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerHeartbeatEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerHeartbeatEvent) GetActiveBranches() int32 {
	if x != nil {
		return x.ActiveBranches
	}
	return 0
}

func (x *ServerHeartbeatEvent) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *ServerHeartbeatEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ErrorReportEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // info, warning, error, critical
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReportEvent) Reset() {
	*x = ErrorReportEvent{}
	mi := &file_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReportEvent) ProtoMessage() {}

func (x *ErrorReportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReportEvent.ProtoReflect.Descriptor instead.
func (*ErrorReportEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorReportEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ErrorReportEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ErrorReportEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorReportEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ErrorReportEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TenantMetricsEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TotalSales     float64                `protobuf:"fixed64,2,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	TotalOrders    int32                  `protobuf:"varint,3,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantMetricsEvent) Reset() {
	*x = TenantMetricsEvent{}
	mi := &file_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMetricsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMetricsEvent) ProtoMessage() {}

func (x *TenantMetricsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMetricsEvent.ProtoReflect.Descriptor instead.
func (*TenantMetricsEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{20}
}

func (x *TenantMetricsEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantMetricsEvent) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *TenantMetricsEvent) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *TenantMetricsEvent) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *TenantMetricsEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x11aburpos.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x02\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\x06source\x18\x05 \x01(\v2\x1e.aburpos.events.v1.EventSourceR\x06source\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12<\n" +
	"\bmetadata\x18\a \x01(\v2 .aburpos.events.v1.EventMetadataR\bmetadata\"\x88\x01\n" +
	"\vEventSource\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\tR\bbranchId\x12%\n" +
	"\x0eworkstation_id\x18\x04 \x01(\tR\rworkstationId\"r\n" +
	"\rEventMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\"\xba\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\x01R\bdiscount\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\"\x8a\x04\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"trx_number\x18\x02 \x01(\tR\ttrxNumber\x12$\n" +
	"\vcustomer_id\x18\x03 \x01(\x03H\x00R\n" +
	"customerId\x88\x01\x01\x12#\n" +
	"\rcustomer_name\x18\x04 \x01(\tR\fcustomerName\x122\n" +
	"\x05items\x18\x05 \x03(\v2\x1c.aburpos.events.v1.OrderItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x06 \x01(\x01R\bsubtotal\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\a \x01(\x01R\ttaxAmount\x12\x1a\n" +
	"\bdiscount\x18\b \x01(\x01R\bdiscount\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x12%\n" +
	"\x0epayment_method\x18\n" +
	" \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\f \x01(\x03R\tcashierId\x12\x19\n" +
	"\bshift_id\x18\r \x01(\x03R\ashiftId\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_customer_id\"\xb1\x01\n" +
	"\x13OrderCompletedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"trx_number\x18\x02 \x01(\tR\ttrxNumber\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xc9\x01\n" +
	"\x13OrderCancelledEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"trx_number\x18\x02 \x01(\tR\ttrxNumber\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\fcancelled_by\x18\x04 \x01(\x03R\vcancelledBy\x12=\n" +
	"\fcancelled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"=\n" +
	"\bCardData\x12\x14\n" +
	"\x05last4\x18\x01 \x01(\tR\x05last4\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\"9\n" +
	"\aUPIData\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x10\n" +
	"\x03vpa\x18\x02 \x01(\tR\x03vpa\"\x91\x03\n" +
	"\x15PaymentProcessedEvent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12=\n" +
	"\tcard_data\x18\x06 \x01(\v2\x1b.aburpos.events.v1.CardDataH\x00R\bcardData\x88\x01\x01\x12:\n" +
	"\bupi_data\x18\a \x01(\v2\x1a.aburpos.events.v1.UPIDataH\x01R\aupiData\x88\x01\x01\x12!\n" +
	"\fprocessed_by\x18\b \x01(\x03R\vprocessedBy\x12=\n" +
	"\fprocessed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAtB\f\n" +
	"\n" +
	"_card_dataB\v\n" +
	"\t_upi_data\"\xdd\x01\n" +
	"\x11RefundIssuedEvent\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\x03R\brefundId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\x03R\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1f\n" +
	"\vrefunded_by\x18\x05 \x01(\x03R\n" +
	"refundedBy\x12;\n" +
	"\vrefunded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\"\xc8\x01\n" +
	"\x12LowStockAlertEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12#\n" +
	"\rcurrent_stock\x18\x04 \x01(\x05R\fcurrentStock\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1b\n" +
	"\tbranch_id\x18\x06 \x01(\tR\bbranchId\"\xe3\x02\n" +
	"\x11StockUpdatedEvent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12%\n" +
	"\x0eprevious_stock\x18\x04 \x01(\x05R\rpreviousStock\x12\x1b\n" +
	"\tnew_stock\x18\x05 \x01(\x05R\bnewStock\x12\x1f\n" +
	"\vchange_type\x18\x06 \x01(\tR\n" +
	"changeType\x12#\n" +
	"\rchange_amount\x18\a \x01(\x05R\fchangeAmount\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\x03R\tupdatedBy\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd1\x02\n" +
	"\rAuditLogEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"old_values\x18\x06 \x01(\fR\toldValues\x12\x1d\n" +
	"\n" +
	"new_values\x18\a \x01(\fR\tnewValues\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x03\n" +
	"\x11MetricsBatchEvent\x12%\n" +
	"\x0eworkstation_id\x18\x01 \x01(\tR\rworkstationId\x12K\n" +
	"\ametrics\x18\x02 \x03(\v21.aburpos.events.v1.MetricsBatchEvent.MetricsEntryR\ametrics\x12H\n" +
	"\x06labels\x18\x03 \x03(\v20.aburpos.events.v1.MetricsBatchEvent.LabelsEntryR\x06labels\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x12NotificationTarget\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\"B\n" +
	"\x12NotificationAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\xe5\x02\n" +
	"\x11NotificationEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12=\n" +
	"\x06target\x18\x05 \x01(\v2%.aburpos.events.v1.NotificationTargetR\x06target\x12B\n" +
	"\x06action\x18\x06 \x01(\v2%.aburpos.events.v1.NotificationActionH\x00R\x06action\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01B\t\n" +
	"\a_actionB\r\n" +
	"\v_expires_at\"\x8a\x02\n" +
	"\x14ServerHeartbeatEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"server_url\x18\x02 \x01(\tR\tserverUrl\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12'\n" +
	"\x0factive_branches\x18\x05 \x01(\x05R\x0eactiveBranches\x12!\n" +
	"\factive_users\x18\x06 \x01(\x05R\vactiveUsers\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb9\x01\n" +
	"\x10ErrorReportEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd8\x01\n" +
	"\x12TenantMetricsEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtotal_sales\x18\x02 \x01(\x01R\n" +
	"totalSales\x12!\n" +
	"\ftotal_orders\x18\x03 \x01(\x05R\vtotalOrders\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\"Z github.com/aburpos/pkg/pb/eventsb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: aburpos.events.v1.EventEnvelope
	(*EventSource)(nil),           // 1: aburpos.events.v1.EventSource
	(*EventMetadata)(nil),         // 2: aburpos.events.v1.EventMetadata
	(*OrderItem)(nil),             // 3: aburpos.events.v1.OrderItem
	(*OrderCreatedEvent)(nil),     // 4: aburpos.events.v1.OrderCreatedEvent
	(*OrderCompletedEvent)(nil),   // 5: aburpos.events.v1.OrderCompletedEvent
	(*OrderCancelledEvent)(nil),   // 6: aburpos.events.v1.OrderCancelledEvent
	(*CardData)(nil),              // 7: aburpos.events.v1.CardData
	(*UPIData)(nil),               // 8: aburpos.events.v1.UPIData
	(*PaymentProcessedEvent)(nil), // 9: aburpos.events.v1.PaymentProcessedEvent
	(*RefundIssuedEvent)(nil),     // 10: aburpos.events.v1.RefundIssuedEvent
	(*LowStockAlertEvent)(nil),    // 11: aburpos.events.v1.LowStockAlertEvent
	(*StockUpdatedEvent)(nil),     // 12: aburpos.events.v1.StockUpdatedEvent
	(*AuditLogEvent)(nil),         // 13: aburpos.events.v1.AuditLogEvent
	(*MetricsBatchEvent)(nil),     // 14: aburpos.events.v1.MetricsBatchEvent
	(*NotificationTarget)(nil),    // 15: aburpos.events.v1.NotificationTarget
	(*NotificationAction)(nil),    // 16: aburpos.events.v1.NotificationAction
	(*NotificationEvent)(nil),     // 17: aburpos.events.v1.NotificationEvent
	(*ServerHeartbeatEvent)(nil),  // 18: aburpos.events.v1.ServerHeartbeatEvent
	(*ErrorReportEvent)(nil),      // 19: aburpos.events.v1.ErrorReportEvent
	(*TenantMetricsEvent)(nil),    // 20: aburpos.events.v1.TenantMetricsEvent
	nil,                           // 21: aburpos.events.v1.MetricsBatchEvent.MetricsEntry
	nil,                           // 22: aburpos.events.v1.MetricsBatchEvent.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_events_proto_depIdxs = []int32{
	23, // 0: aburpos.events.v1.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: aburpos.events.v1.EventEnvelope.source:type_name -> aburpos.events.v1.EventSource
	2,  // 2: aburpos.events.v1.EventEnvelope.metadata:type_name -> aburpos.events.v1.EventMetadata
	3,  // 3: aburpos.events.v1.OrderCreatedEvent.items:type_name -> aburpos.events.v1.OrderItem
	23, // 4: aburpos.events.v1.OrderCreatedEvent.created_at:type_name -> google.protobuf.Timestamp
	23, // 5: aburpos.events.v1.OrderCompletedEvent.completed_at:type_name -> google.protobuf.Timestamp
	23, // 6: aburpos.events.v1.OrderCancelledEvent.cancelled_at:type_name -> google.protobuf.Timestamp
	7,  // 7: aburpos.events.v1.PaymentProcessedEvent.card_data:type_name -> aburpos.events.v1.CardData
	8,  // 8: aburpos.events.v1.PaymentProcessedEvent.upi_data:type_name -> aburpos.events.v1.UPIData
	23, // 9: aburpos.events.v1.PaymentProcessedEvent.processed_at:type_name -> google.protobuf.Timestamp
	23, // 10: aburpos.events.v1.RefundIssuedEvent.refunded_at:type_name -> google.protobuf.Timestamp
	23, // 11: aburpos.events.v1.StockUpdatedEvent.updated_at:type_name -> google.protobuf.Timestamp
	23, // 12: aburpos.events.v1.AuditLogEvent.timestamp:type_name -> google.protobuf.Timestamp
	21, // 13: aburpos.events.v1.MetricsBatchEvent.metrics:type_name -> aburpos.events.v1.MetricsBatchEvent.MetricsEntry
	22, // 14: aburpos.events.v1.MetricsBatchEvent.labels:type_name -> aburpos.events.v1.MetricsBatchEvent.LabelsEntry
	23, // 15: aburpos.events.v1.MetricsBatchEvent.timestamp:type_name -> google.protobuf.Timestamp
	15, // 16: aburpos.events.v1.NotificationEvent.target:type_name -> aburpos.events.v1.NotificationTarget
	16, // 17: aburpos.events.v1.NotificationEvent.action:type_name -> aburpos.events.v1.NotificationAction
	23, // 18: aburpos.events.v1.NotificationEvent.expires_at:type_name -> google.protobuf.Timestamp
	23, // 19: aburpos.events.v1.ServerHeartbeatEvent.timestamp:type_name -> google.protobuf.Timestamp
	23, // 20: aburpos.events.v1.ErrorReportEvent.timestamp:type_name -> google.protobuf.Timestamp
	23, // 21: aburpos.events.v1.TenantMetricsEvent.timestamp:type_name -> google.protobuf.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_events_proto_msgTypes[9].OneofWrappers = []any{}
	file_events_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
