// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pos_service.proto

package pos

import (
	context "context"
	events "github.com/yahyaoncloud/pkg/pb/events"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	POSEventService_EventStream_FullMethodName       = "/aburpos.pos.v1.POSEventService/EventStream"
	POSEventService_Heartbeat_FullMethodName         = "/aburpos.pos.v1.POSEventService/Heartbeat"
	POSEventService_SubscribeCommands_FullMethodName = "/aburpos.pos.v1.POSEventService/SubscribeCommands"
	POSEventService_PublishEvent_FullMethodName      = "/aburpos.pos.v1.POSEventService/PublishEvent"
	POSEventService_Register_FullMethodName          = "/aburpos.pos.v1.POSEventService/Register"
	POSEventService_VerifyTenant_FullMethodName      = "/aburpos.pos.v1.POSEventService/VerifyTenant"
)

// POSEventServiceClient is the client API for POSEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type POSEventServiceClient interface {
	// Bidirectional stream for events
	// POS sends events (orders, payments, inventory, etc.)
	// Central can send back commands or acknowledgments
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[events.EventEnvelope, events.EventEnvelope], error)
	// Unary heartbeat with immediate response
	// Used for health checks and receiving pending commands
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Server-side stream for commands from Central to POS
	// POS subscribes once and receives commands as they're issued
	SubscribeCommands(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
	// Unary call to publish a single event (fallback for non-streaming)
	PublishEvent(ctx context.Context, in *events.EventEnvelope, opts ...grpc.CallOption) (*PublishResponse, error)
	// Register POS server with Central (Legacy/Direct)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Verify Tenant (New Flow: Code + Email -> Metadata)
	VerifyTenant(ctx context.Context, in *VerifyTenantRequest, opts ...grpc.CallOption) (*VerifyTenantResponse, error)
}

type pOSEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPOSEventServiceClient(cc grpc.ClientConnInterface) POSEventServiceClient {
	return &pOSEventServiceClient{cc}
}

func (c *pOSEventServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[events.EventEnvelope, events.EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &POSEventService_ServiceDesc.Streams[0], POSEventService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[events.EventEnvelope, events.EventEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type POSEventService_EventStreamClient = grpc.BidiStreamingClient[events.EventEnvelope, events.EventEnvelope]

func (c *pOSEventServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, POSEventService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pOSEventServiceClient) SubscribeCommands(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &POSEventService_ServiceDesc.Streams[1], POSEventService_SubscribeCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type POSEventService_SubscribeCommandsClient = grpc.ServerStreamingClient[Command]

func (c *pOSEventServiceClient) PublishEvent(ctx context.Context, in *events.EventEnvelope, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, POSEventService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pOSEventServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, POSEventService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pOSEventServiceClient) VerifyTenant(ctx context.Context, in *VerifyTenantRequest, opts ...grpc.CallOption) (*VerifyTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTenantResponse)
	err := c.cc.Invoke(ctx, POSEventService_VerifyTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// POSEventServiceServer is the server API for POSEventService service.
// All implementations must embed UnimplementedPOSEventServiceServer
// for forward compatibility.
type POSEventServiceServer interface {
	// Bidirectional stream for events
	// POS sends events (orders, payments, inventory, etc.)
	// Central can send back commands or acknowledgments
	EventStream(grpc.BidiStreamingServer[events.EventEnvelope, events.EventEnvelope]) error
	// Unary heartbeat with immediate response
	// Used for health checks and receiving pending commands
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Server-side stream for commands from Central to POS
	// POS subscribes once and receives commands as they're issued
	SubscribeCommands(*SubscribeRequest, grpc.ServerStreamingServer[Command]) error
	// Unary call to publish a single event (fallback for non-streaming)
	PublishEvent(context.Context, *events.EventEnvelope) (*PublishResponse, error)
	// Register POS server with Central (Legacy/Direct)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Verify Tenant (New Flow: Code + Email -> Metadata)
	VerifyTenant(context.Context, *VerifyTenantRequest) (*VerifyTenantResponse, error)
	mustEmbedUnimplementedPOSEventServiceServer()
}

// UnimplementedPOSEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPOSEventServiceServer struct{}

func (UnimplementedPOSEventServiceServer) EventStream(grpc.BidiStreamingServer[events.EventEnvelope, events.EventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedPOSEventServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPOSEventServiceServer) SubscribeCommands(*SubscribeRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCommands not implemented")
}
func (UnimplementedPOSEventServiceServer) PublishEvent(context.Context, *events.EventEnvelope) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedPOSEventServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPOSEventServiceServer) VerifyTenant(context.Context, *VerifyTenantRequest) (*VerifyTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyTenant not implemented")
}
func (UnimplementedPOSEventServiceServer) mustEmbedUnimplementedPOSEventServiceServer() {}
func (UnimplementedPOSEventServiceServer) testEmbeddedByValue()                         {}

// UnsafePOSEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to POSEventServiceServer will
// result in compilation errors.
type UnsafePOSEventServiceServer interface {
	mustEmbedUnimplementedPOSEventServiceServer()
}

func RegisterPOSEventServiceServer(s grpc.ServiceRegistrar, srv POSEventServiceServer) {
	// If the following call panics, it indicates UnimplementedPOSEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&POSEventService_ServiceDesc, srv)
}

func _POSEventService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(POSEventServiceServer).EventStream(&grpc.GenericServerStream[events.EventEnvelope, events.EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type POSEventService_EventStreamServer = grpc.BidiStreamingServer[events.EventEnvelope, events.EventEnvelope]

func _POSEventService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSEventServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSEventService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSEventServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _POSEventService_SubscribeCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(POSEventServiceServer).SubscribeCommands(m, &grpc.GenericServerStream[SubscribeRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type POSEventService_SubscribeCommandsServer = grpc.ServerStreamingServer[Command]

func _POSEventService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(events.EventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSEventServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSEventService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSEventServiceServer).PublishEvent(ctx, req.(*events.EventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _POSEventService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSEventServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSEventService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSEventServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _POSEventService_VerifyTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POSEventServiceServer).VerifyTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: POSEventService_VerifyTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POSEventServiceServer).VerifyTenant(ctx, req.(*VerifyTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// POSEventService_ServiceDesc is the grpc.ServiceDesc for POSEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var POSEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aburpos.pos.v1.POSEventService",
	HandlerType: (*POSEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _POSEventService_Heartbeat_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _POSEventService_PublishEvent_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _POSEventService_Register_Handler,
		},
		{
			MethodName: "VerifyTenant",
			Handler:    _POSEventService_VerifyTenant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _POSEventService_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeCommands",
			Handler:       _POSEventService_SubscribeCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pos_service.proto",
}

const (
	ProvisioningService_StreamProvisioning_FullMethodName  = "/aburpos.pos.v1.ProvisioningService/StreamProvisioning"
	ProvisioningService_ConfirmProvisioning_FullMethodName = "/aburpos.pos.v1.ProvisioningService/ConfirmProvisioning"
)

// ProvisioningServiceClient is the client API for ProvisioningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvisioningServiceClient interface {
	// Stream provisioning events to POS during initial setup
	StreamProvisioning(ctx context.Context, in *ProvisioningRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProvisioningEvent], error)
	// Confirm provisioning completion
	ConfirmProvisioning(ctx context.Context, in *ProvisioningConfirmation, opts ...grpc.CallOption) (*ProvisioningResponse, error)
}

type provisioningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisioningServiceClient(cc grpc.ClientConnInterface) ProvisioningServiceClient {
	return &provisioningServiceClient{cc}
}

func (c *provisioningServiceClient) StreamProvisioning(ctx context.Context, in *ProvisioningRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProvisioningEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProvisioningService_ServiceDesc.Streams[0], ProvisioningService_StreamProvisioning_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProvisioningRequest, ProvisioningEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisioningService_StreamProvisioningClient = grpc.ServerStreamingClient[ProvisioningEvent]

func (c *provisioningServiceClient) ConfirmProvisioning(ctx context.Context, in *ProvisioningConfirmation, opts ...grpc.CallOption) (*ProvisioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisioningResponse)
	err := c.cc.Invoke(ctx, ProvisioningService_ConfirmProvisioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisioningServiceServer is the server API for ProvisioningService service.
// All implementations must embed UnimplementedProvisioningServiceServer
// for forward compatibility.
type ProvisioningServiceServer interface {
	// Stream provisioning events to POS during initial setup
	StreamProvisioning(*ProvisioningRequest, grpc.ServerStreamingServer[ProvisioningEvent]) error
	// Confirm provisioning completion
	ConfirmProvisioning(context.Context, *ProvisioningConfirmation) (*ProvisioningResponse, error)
	mustEmbedUnimplementedProvisioningServiceServer()
}

// UnimplementedProvisioningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisioningServiceServer struct{}

func (UnimplementedProvisioningServiceServer) StreamProvisioning(*ProvisioningRequest, grpc.ServerStreamingServer[ProvisioningEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamProvisioning not implemented")
}
func (UnimplementedProvisioningServiceServer) ConfirmProvisioning(context.Context, *ProvisioningConfirmation) (*ProvisioningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmProvisioning not implemented")
}
func (UnimplementedProvisioningServiceServer) mustEmbedUnimplementedProvisioningServiceServer() {}
func (UnimplementedProvisioningServiceServer) testEmbeddedByValue()                             {}

// UnsafeProvisioningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisioningServiceServer will
// result in compilation errors.
type UnsafeProvisioningServiceServer interface {
	mustEmbedUnimplementedProvisioningServiceServer()
}

func RegisterProvisioningServiceServer(s grpc.ServiceRegistrar, srv ProvisioningServiceServer) {
	// If the following call panics, it indicates UnimplementedProvisioningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisioningService_ServiceDesc, srv)
}

func _ProvisioningService_StreamProvisioning_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisioningRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisioningServiceServer).StreamProvisioning(m, &grpc.GenericServerStream[ProvisioningRequest, ProvisioningEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisioningService_StreamProvisioningServer = grpc.ServerStreamingServer[ProvisioningEvent]

func _ProvisioningService_ConfirmProvisioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisioningConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisioningServiceServer).ConfirmProvisioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisioningService_ConfirmProvisioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisioningServiceServer).ConfirmProvisioning(ctx, req.(*ProvisioningConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvisioningService_ServiceDesc is the grpc.ServiceDesc for ProvisioningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisioningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aburpos.pos.v1.ProvisioningService",
	HandlerType: (*ProvisioningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmProvisioning",
			Handler:    _ProvisioningService_ConfirmProvisioning_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProvisioning",
			Handler:       _ProvisioningService_StreamProvisioning_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pos_service.proto",
}

const (
	NotificationService_SubscribeNotifications_FullMethodName  = "/aburpos.pos.v1.NotificationService/SubscribeNotifications"
	NotificationService_AcknowledgeNotification_FullMethodName = "/aburpos.pos.v1.NotificationService/AcknowledgeNotification"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	// Subscribe to notifications for a tenant/branch/workstation
	SubscribeNotifications(ctx context.Context, in *NotificationSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	// Acknowledge a notification
	AcknowledgeNotification(ctx context.Context, in *NotificationAck, opts ...grpc.CallOption) (*NotificationAckResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SubscribeNotifications(ctx context.Context, in *NotificationSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NotificationService_ServiceDesc.Streams[0], NotificationService_SubscribeNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotificationSubscribeRequest, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationService_SubscribeNotificationsClient = grpc.ServerStreamingClient[Notification]

func (c *notificationServiceClient) AcknowledgeNotification(ctx context.Context, in *NotificationAck, opts ...grpc.CallOption) (*NotificationAckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationAckResponse)
	err := c.cc.Invoke(ctx, NotificationService_AcknowledgeNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	// Subscribe to notifications for a tenant/branch/workstation
	SubscribeNotifications(*NotificationSubscribeRequest, grpc.ServerStreamingServer[Notification]) error
	// Acknowledge a notification
	AcknowledgeNotification(context.Context, *NotificationAck) (*NotificationAckResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) SubscribeNotifications(*NotificationSubscribeRequest, grpc.ServerStreamingServer[Notification]) error {
	return status.Error(codes.Unimplemented, "method SubscribeNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) AcknowledgeNotification(context.Context, *NotificationAck) (*NotificationAckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeNotification not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SubscribeNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotificationSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationServiceServer).SubscribeNotifications(m, &grpc.GenericServerStream[NotificationSubscribeRequest, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NotificationService_SubscribeNotificationsServer = grpc.ServerStreamingServer[Notification]

func _NotificationService_AcknowledgeNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).AcknowledgeNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_AcknowledgeNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).AcknowledgeNotification(ctx, req.(*NotificationAck))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aburpos.pos.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcknowledgeNotification",
			Handler:    _NotificationService_AcknowledgeNotification_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeNotifications",
			Handler:       _NotificationService_SubscribeNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pos_service.proto",
}
