// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pos_service.proto

package pos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	events "github.com/yahyaoncloud/pkg/pb/events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command types
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED       CommandType = 0
	CommandType_COMMAND_TYPE_PRODUCT_SYNC      CommandType = 1
	CommandType_COMMAND_TYPE_CONFIG_UPDATE     CommandType = 2
	CommandType_COMMAND_TYPE_FORCE_LOGOUT      CommandType = 3
	CommandType_COMMAND_TYPE_LOCK_TENANT       CommandType = 4
	CommandType_COMMAND_TYPE_UNLOCK_TENANT     CommandType = 5
	CommandType_COMMAND_TYPE_SOFTWARE_UPDATE   CommandType = 6
	CommandType_COMMAND_TYPE_PUSH_NOTIFICATION CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_PRODUCT_SYNC",
		2: "COMMAND_TYPE_CONFIG_UPDATE",
		3: "COMMAND_TYPE_FORCE_LOGOUT",
		4: "COMMAND_TYPE_LOCK_TENANT",
		5: "COMMAND_TYPE_UNLOCK_TENANT",
		6: "COMMAND_TYPE_SOFTWARE_UPDATE",
		7: "COMMAND_TYPE_PUSH_NOTIFICATION",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":       0,
		"COMMAND_TYPE_PRODUCT_SYNC":      1,
		"COMMAND_TYPE_CONFIG_UPDATE":     2,
		"COMMAND_TYPE_FORCE_LOGOUT":      3,
		"COMMAND_TYPE_LOCK_TENANT":       4,
		"COMMAND_TYPE_UNLOCK_TENANT":     5,
		"COMMAND_TYPE_SOFTWARE_UPDATE":   6,
		"COMMAND_TYPE_PUSH_NOTIFICATION": 7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_pos_service_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_pos_service_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BranchId       string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	WorkstationId  string                 `protobuf:"bytes,3,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	ServerUrl      string                 `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // online, offline, maintenance
	Version        string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	ActiveBranches int32                  `protobuf:"varint,7,opt,name=active_branches,json=activeBranches,proto3" json:"active_branches,omitempty"`
	ActiveUsers    int32                  `protobuf:"varint,8,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	Usage          *UsageStats            `protobuf:"bytes,9,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HeartbeatRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

func (x *HeartbeatRequest) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveBranches() int32 {
	if x != nil {
		return x.ActiveBranches
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *HeartbeatRequest) GetUsage() *UsageStats {
	if x != nil {
		return x.Usage
	}
	return nil
}

type UsageStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrdersToday    int32                  `protobuf:"varint,1,opt,name=orders_today,json=ordersToday,proto3" json:"orders_today,omitempty"`
	SalesToday     float64                `protobuf:"fixed64,2,opt,name=sales_today,json=salesToday,proto3" json:"sales_today,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_pos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{1}
}

func (x *UsageStats) GetOrdersToday() int32 {
	if x != nil {
		return x.OrdersToday
	}
	return 0
}

func (x *UsageStats) GetSalesToday() float64 {
	if x != nil {
		return x.SalesToday
	}
	return 0
}

func (x *UsageStats) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *UsageStats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged    bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	PendingCommands []*Command             `protobuf:"bytes,3,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	LicenseStatus   *LicenseStatus         `protobuf:"bytes,4,opt,name=license_status,json=licenseStatus,proto3" json:"license_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pos_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HeartbeatResponse) GetPendingCommands() []*Command {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

func (x *HeartbeatResponse) GetLicenseStatus() *LicenseStatus {
	if x != nil {
		return x.LicenseStatus
	}
	return nil
}

type LicenseStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DaysRemaining  int32                  `protobuf:"varint,3,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	WarningMessage string                 `protobuf:"bytes,4,opt,name=warning_message,json=warningMessage,proto3" json:"warning_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LicenseStatus) Reset() {
	*x = LicenseStatus{}
	mi := &file_pos_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseStatus) ProtoMessage() {}

func (x *LicenseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseStatus.ProtoReflect.Descriptor instead.
func (*LicenseStatus) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{3}
}

func (x *LicenseStatus) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *LicenseStatus) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LicenseStatus) GetDaysRemaining() int32 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

func (x *LicenseStatus) GetWarningMessage() string {
	if x != nil {
		return x.WarningMessage
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	WorkstationId string                 `protobuf:"bytes,3,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	CommandTypes  []string               `protobuf:"bytes,4,rep,name=command_types,json=commandTypes,proto3" json:"command_types,omitempty"` // Filter for specific command types (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pos_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubscribeRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *SubscribeRequest) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

func (x *SubscribeRequest) GetCommandTypes() []string {
	if x != nil {
		return x.CommandTypes
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-serialized command data
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"` // low, normal, high, urgent
	RequiresAck   bool                   `protobuf:"varint,6,opt,name=requires_ack,json=requiresAck,proto3" json:"requires_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pos_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Command) GetRequiresAck() bool {
	if x != nil {
		return x.RequiresAck
	}
	return false
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pos_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{6}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	BranchId      string                 `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	WorkstationId string                 `protobuf:"bytes,4,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	LicenseKey    string                 `protobuf:"bytes,5,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	ServerUrl     string                 `protobuf:"bytes,6,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Feature flags the POS supports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pos_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *RegisterRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *RegisterRequest) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

func (x *RegisterRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

func (x *RegisterRequest) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pos_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ServerConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	EventBatchSize           int32                  `protobuf:"varint,2,opt,name=event_batch_size,json=eventBatchSize,proto3" json:"event_batch_size,omitempty"`
	ReconnectDelaySeconds    int32                  `protobuf:"varint,3,opt,name=reconnect_delay_seconds,json=reconnectDelaySeconds,proto3" json:"reconnect_delay_seconds,omitempty"`
	CompressionEnabled       bool                   `protobuf:"varint,4,opt,name=compression_enabled,json=compressionEnabled,proto3" json:"compression_enabled,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_pos_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServerConfig) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *ServerConfig) GetEventBatchSize() int32 {
	if x != nil {
		return x.EventBatchSize
	}
	return 0
}

func (x *ServerConfig) GetReconnectDelaySeconds() int32 {
	if x != nil {
		return x.ReconnectDelaySeconds
	}
	return 0
}

func (x *ServerConfig) GetCompressionEnabled() bool {
	if x != nil {
		return x.CompressionEnabled
	}
	return false
}

type ProvisioningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LicenseKey    string                 `protobuf:"bytes,2,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningRequest) Reset() {
	*x = ProvisioningRequest{}
	mi := &file_pos_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningRequest) ProtoMessage() {}

func (x *ProvisioningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningRequest.ProtoReflect.Descriptor instead.
func (*ProvisioningRequest) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProvisioningRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProvisioningRequest) GetLicenseKey() string {
	if x != nil {
		return x.LicenseKey
	}
	return ""
}

type ProvisioningEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventType       string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // setup_started, database_ready, admin_created, setup_complete
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Additional JSON data
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProvisioningEvent) Reset() {
	*x = ProvisioningEvent{}
	mi := &file_pos_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningEvent) ProtoMessage() {}

func (x *ProvisioningEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningEvent.ProtoReflect.Descriptor instead.
func (*ProvisioningEvent) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{11}
}

func (x *ProvisioningEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProvisioningEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProvisioningEvent) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ProvisioningEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProvisioningConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DatabaseReady bool                   `protobuf:"varint,4,opt,name=database_ready,json=databaseReady,proto3" json:"database_ready,omitempty"`
	AdminCreated  bool                   `protobuf:"varint,5,opt,name=admin_created,json=adminCreated,proto3" json:"admin_created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningConfirmation) Reset() {
	*x = ProvisioningConfirmation{}
	mi := &file_pos_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningConfirmation) ProtoMessage() {}

func (x *ProvisioningConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningConfirmation.ProtoReflect.Descriptor instead.
func (*ProvisioningConfirmation) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{12}
}

func (x *ProvisioningConfirmation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProvisioningConfirmation) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProvisioningConfirmation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProvisioningConfirmation) GetDatabaseReady() bool {
	if x != nil {
		return x.DatabaseReady
	}
	return false
}

func (x *ProvisioningConfirmation) GetAdminCreated() bool {
	if x != nil {
		return x.AdminCreated
	}
	return false
}

type ProvisioningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	NextStep      string                 `protobuf:"bytes,2,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisioningResponse) Reset() {
	*x = ProvisioningResponse{}
	mi := &file_pos_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningResponse) ProtoMessage() {}

func (x *ProvisioningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningResponse.ProtoReflect.Descriptor instead.
func (*ProvisioningResponse) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{13}
}

func (x *ProvisioningResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ProvisioningResponse) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

type NotificationSubscribeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BranchId          string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	WorkstationId     string                 `protobuf:"bytes,3,opt,name=workstation_id,json=workstationId,proto3" json:"workstation_id,omitempty"`
	UserId            string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationTypes []string               `protobuf:"bytes,5,rep,name=notification_types,json=notificationTypes,proto3" json:"notification_types,omitempty"` // Filter by type
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationSubscribeRequest) Reset() {
	*x = NotificationSubscribeRequest{}
	mi := &file_pos_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSubscribeRequest) ProtoMessage() {}

func (x *NotificationSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSubscribeRequest.ProtoReflect.Descriptor instead.
func (*NotificationSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{14}
}

func (x *NotificationSubscribeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NotificationSubscribeRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *NotificationSubscribeRequest) GetWorkstationId() string {
	if x != nil {
		return x.WorkstationId
	}
	return ""
}

func (x *NotificationSubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationSubscribeRequest) GetNotificationTypes() []string {
	if x != nil {
		return x.NotificationTypes
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RequiresAck   bool                   `protobuf:"varint,9,opt,name=requires_ack,json=requiresAck,proto3" json:"requires_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_pos_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{15}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Notification) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Notification) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Notification) GetRequiresAck() bool {
	if x != nil {
		return x.RequiresAck
	}
	return false
}

type NotificationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AckTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ack_time,json=ackTime,proto3" json:"ack_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationAck) Reset() {
	*x = NotificationAck{}
	mi := &file_pos_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAck) ProtoMessage() {}

func (x *NotificationAck) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAck.ProtoReflect.Descriptor instead.
func (*NotificationAck) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{16}
}

func (x *NotificationAck) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationAck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationAck) GetAckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AckTime
	}
	return nil
}

type NotificationAckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAckResponse) Reset() {
	*x = NotificationAckResponse{}
	mi := &file_pos_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAckResponse) ProtoMessage() {}

func (x *NotificationAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pos_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAckResponse.ProtoReflect.Descriptor instead.
func (*NotificationAckResponse) Descriptor() ([]byte, []int) {
	return file_pos_service_proto_rawDescGZIP(), []int{17}
}

func (x *NotificationAckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pos_service_proto protoreflect.FileDescriptor

const file_pos_service_proto_rawDesc = "" +
	"\n" +
	"\x11pos_service.proto\x12\x0eaburpos.pos.v1\x1a\fevents.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12%\n" +
	"\x0eworkstation_id\x18\x03 \x01(\tR\rworkstationId\x12\x1d\n" +
	"\n" +
	"server_url\x18\x04 \x01(\tR\tserverUrl\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12'\n" +
	"\x0factive_branches\x18\a \x01(\x05R\x0eactiveBranches\x12!\n" +
	"\factive_users\x18\b \x01(\x05R\vactiveUsers\x120\n" +
	"\x05usage\x18\t \x01(\v2\x1a.aburpos.pos.v1.UsageStatsR\x05usage\"\xa0\x01\n" +
	"\n" +
	"UsageStats\x12!\n" +
	"\forders_today\x18\x01 \x01(\x05R\vordersToday\x12\x1f\n" +
	"\vsales_today\x18\x02 \x01(\x01R\n" +
	"salesToday\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\xfe\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12B\n" +
	"\x10pending_commands\x18\x03 \x03(\v2\x17.aburpos.pos.v1.CommandR\x0fpendingCommands\x12D\n" +
	"\x0elicense_status\x18\x04 \x01(\v2\x1d.aburpos.pos.v1.LicenseStatusR\rlicenseStatus\"\xb0\x01\n" +
	"\rLicenseStatus\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0edays_remaining\x18\x03 \x01(\x05R\rdaysRemaining\x12'\n" +
	"\x0fwarning_message\x18\x04 \x01(\tR\x0ewarningMessage\"\x98\x01\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12%\n" +
	"\x0eworkstation_id\x18\x03 \x01(\tR\rworkstationId\x12#\n" +
	"\rcommand_types\x18\x04 \x03(\tR\fcommandTypes\"\xc0\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12!\n" +
	"\frequires_ack\x18\x06 \x01(\bR\vrequiresAck\"`\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x85\x03\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_code\x18\x02 \x01(\tR\n" +
	"tenantCode\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\tR\bbranchId\x12%\n" +
	"\x0eworkstation_id\x18\x04 \x01(\tR\rworkstationId\x12\x1f\n" +
	"\vlicense_key\x18\x05 \x01(\tR\n" +
	"licenseKey\x12\x1d\n" +
	"\n" +
	"server_url\x18\x06 \x01(\tR\tserverUrl\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12U\n" +
	"\fcapabilities\x18\b \x03(\v21.aburpos.pos.v1.RegisterRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x124\n" +
	"\x06config\x18\x04 \x01(\v2\x1c.aburpos.pos.v1.ServerConfigR\x06config\"\xdf\x01\n" +
	"\fServerConfig\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x05R\x18heartbeatIntervalSeconds\x12(\n" +
	"\x10event_batch_size\x18\x02 \x01(\x05R\x0eeventBatchSize\x126\n" +
	"\x17reconnect_delay_seconds\x18\x03 \x01(\x05R\x15reconnectDelaySeconds\x12/\n" +
	"\x13compression_enabled\x18\x04 \x01(\bR\x12compressionEnabled\"S\n" +
	"\x13ProvisioningRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlicense_key\x18\x02 \x01(\tR\n" +
	"licenseKey\"\x8b\x01\n" +
	"\x11ProvisioningEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x05R\x0fprogressPercent\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xb7\x01\n" +
	"\x18ProvisioningConfirmation\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0edatabase_ready\x18\x04 \x01(\bR\rdatabaseReady\x12#\n" +
	"\radmin_created\x18\x05 \x01(\bR\fadminCreated\"W\n" +
	"\x14ProvisioningResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1b\n" +
	"\tnext_step\x18\x02 \x01(\tR\bnextStep\"\xc7\x01\n" +
	"\x1cNotificationSubscribeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12%\n" +
	"\x0eworkstation_id\x18\x03 \x01(\tR\rworkstationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12-\n" +
	"\x12notification_types\x18\x05 \x03(\tR\x11notificationTypes\"\xaa\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\frequires_ack\x18\t \x01(\bR\vrequiresAck\"\x8a\x01\n" +
	"\x0fNotificationAck\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\back_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aackTime\"3\n" +
	"\x17NotificationAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x8d\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_PRODUCT_SYNC\x10\x01\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_CONFIG_UPDATE\x10\x02\x12\x1d\n" +
	"\x19COMMAND_TYPE_FORCE_LOGOUT\x10\x03\x12\x1c\n" +
	"\x18COMMAND_TYPE_LOCK_TENANT\x10\x04\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_UNLOCK_TENANT\x10\x05\x12 \n" +
	"\x1cCOMMAND_TYPE_SOFTWARE_UPDATE\x10\x06\x12\"\n" +
	"\x1eCOMMAND_TYPE_PUSH_NOTIFICATION\x10\a2\xae\x03\n" +
	"\x0fPOSEventService\x12U\n" +
	"\vEventStream\x12 .aburpos.events.v1.EventEnvelope\x1a .aburpos.events.v1.EventEnvelope(\x010\x01\x12P\n" +
	"\tHeartbeat\x12 .aburpos.pos.v1.HeartbeatRequest\x1a!.aburpos.pos.v1.HeartbeatResponse\x12P\n" +
	"\x11SubscribeCommands\x12 .aburpos.pos.v1.SubscribeRequest\x1a\x17.aburpos.pos.v1.Command0\x01\x12Q\n" +
	"\fPublishEvent\x12 .aburpos.events.v1.EventEnvelope\x1a\x1f.aburpos.pos.v1.PublishResponse\x12M\n" +
	"\bRegister\x12\x1f.aburpos.pos.v1.RegisterRequest\x1a .aburpos.pos.v1.RegisterResponse2\xdc\x01\n" +
	"\x13ProvisioningService\x12^\n" +
	"\x12StreamProvisioning\x12#.aburpos.pos.v1.ProvisioningRequest\x1a!.aburpos.pos.v1.ProvisioningEvent0\x01\x12e\n" +
	"\x13ConfirmProvisioning\x12(.aburpos.pos.v1.ProvisioningConfirmation\x1a$.aburpos.pos.v1.ProvisioningResponse2\xe2\x01\n" +
	"\x13NotificationService\x12f\n" +
	"\x16SubscribeNotifications\x12,.aburpos.pos.v1.NotificationSubscribeRequest\x1a\x1c.aburpos.pos.v1.Notification0\x01\x12c\n" +
	"\x17AcknowledgeNotification\x12\x1f.aburpos.pos.v1.NotificationAck\x1a'.aburpos.pos.v1.NotificationAckResponseB\x1fZ\x1dgithub.com/aburpos/pkg/pb/posb\x06proto3"

var (
	file_pos_service_proto_rawDescOnce sync.Once
	file_pos_service_proto_rawDescData []byte
)

func file_pos_service_proto_rawDescGZIP() []byte {
	file_pos_service_proto_rawDescOnce.Do(func() {
		file_pos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pos_service_proto_rawDesc), len(file_pos_service_proto_rawDesc)))
	})
	return file_pos_service_proto_rawDescData
}

var file_pos_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pos_service_proto_goTypes = []any{
	(CommandType)(0),                     // 0: aburpos.pos.v1.CommandType
	(*HeartbeatRequest)(nil),             // 1: aburpos.pos.v1.HeartbeatRequest
	(*UsageStats)(nil),                   // 2: aburpos.pos.v1.UsageStats
	(*HeartbeatResponse)(nil),            // 3: aburpos.pos.v1.HeartbeatResponse
	(*LicenseStatus)(nil),                // 4: aburpos.pos.v1.LicenseStatus
	(*SubscribeRequest)(nil),             // 5: aburpos.pos.v1.SubscribeRequest
	(*Command)(nil),                      // 6: aburpos.pos.v1.Command
	(*PublishResponse)(nil),              // 7: aburpos.pos.v1.PublishResponse
	(*RegisterRequest)(nil),              // 8: aburpos.pos.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 9: aburpos.pos.v1.RegisterResponse
	(*ServerConfig)(nil),                 // 10: aburpos.pos.v1.ServerConfig
	(*ProvisioningRequest)(nil),          // 11: aburpos.pos.v1.ProvisioningRequest
	(*ProvisioningEvent)(nil),            // 12: aburpos.pos.v1.ProvisioningEvent
	(*ProvisioningConfirmation)(nil),     // 13: aburpos.pos.v1.ProvisioningConfirmation
	(*ProvisioningResponse)(nil),         // 14: aburpos.pos.v1.ProvisioningResponse
	(*NotificationSubscribeRequest)(nil), // 15: aburpos.pos.v1.NotificationSubscribeRequest
	(*Notification)(nil),                 // 16: aburpos.pos.v1.Notification
	(*NotificationAck)(nil),              // 17: aburpos.pos.v1.NotificationAck
	(*NotificationAckResponse)(nil),      // 18: aburpos.pos.v1.NotificationAckResponse
	nil,                                  // 19: aburpos.pos.v1.RegisterRequest.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),        // 20: google.protobuf.Timestamp
	(*events.EventEnvelope)(nil),         // 21: aburpos.events.v1.EventEnvelope
}
var file_pos_service_proto_depIdxs = []int32{
	2,  // 0: aburpos.pos.v1.HeartbeatRequest.usage:type_name -> aburpos.pos.v1.UsageStats
	20, // 1: aburpos.pos.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	6,  // 2: aburpos.pos.v1.HeartbeatResponse.pending_commands:type_name -> aburpos.pos.v1.Command
	4,  // 3: aburpos.pos.v1.HeartbeatResponse.license_status:type_name -> aburpos.pos.v1.LicenseStatus
	20, // 4: aburpos.pos.v1.LicenseStatus.expires_at:type_name -> google.protobuf.Timestamp
	20, // 5: aburpos.pos.v1.Command.timestamp:type_name -> google.protobuf.Timestamp
	19, // 6: aburpos.pos.v1.RegisterRequest.capabilities:type_name -> aburpos.pos.v1.RegisterRequest.CapabilitiesEntry
	10, // 7: aburpos.pos.v1.RegisterResponse.config:type_name -> aburpos.pos.v1.ServerConfig
	20, // 8: aburpos.pos.v1.Notification.timestamp:type_name -> google.protobuf.Timestamp
	20, // 9: aburpos.pos.v1.Notification.expires_at:type_name -> google.protobuf.Timestamp
	20, // 10: aburpos.pos.v1.NotificationAck.ack_time:type_name -> google.protobuf.Timestamp
	21, // 11: aburpos.pos.v1.POSEventService.EventStream:input_type -> aburpos.events.v1.EventEnvelope
	1,  // 12: aburpos.pos.v1.POSEventService.Heartbeat:input_type -> aburpos.pos.v1.HeartbeatRequest
	5,  // 13: aburpos.pos.v1.POSEventService.SubscribeCommands:input_type -> aburpos.pos.v1.SubscribeRequest
	21, // 14: aburpos.pos.v1.POSEventService.PublishEvent:input_type -> aburpos.events.v1.EventEnvelope
	8,  // 15: aburpos.pos.v1.POSEventService.Register:input_type -> aburpos.pos.v1.RegisterRequest
	11, // 16: aburpos.pos.v1.ProvisioningService.StreamProvisioning:input_type -> aburpos.pos.v1.ProvisioningRequest
	13, // 17: aburpos.pos.v1.ProvisioningService.ConfirmProvisioning:input_type -> aburpos.pos.v1.ProvisioningConfirmation
	15, // 18: aburpos.pos.v1.NotificationService.SubscribeNotifications:input_type -> aburpos.pos.v1.NotificationSubscribeRequest
	17, // 19: aburpos.pos.v1.NotificationService.AcknowledgeNotification:input_type -> aburpos.pos.v1.NotificationAck
	21, // 20: aburpos.pos.v1.POSEventService.EventStream:output_type -> aburpos.events.v1.EventEnvelope
	3,  // 21: aburpos.pos.v1.POSEventService.Heartbeat:output_type -> aburpos.pos.v1.HeartbeatResponse
	6,  // 22: aburpos.pos.v1.POSEventService.SubscribeCommands:output_type -> aburpos.pos.v1.Command
	7,  // 23: aburpos.pos.v1.POSEventService.PublishEvent:output_type -> aburpos.pos.v1.PublishResponse
	9,  // 24: aburpos.pos.v1.POSEventService.Register:output_type -> aburpos.pos.v1.RegisterResponse
	12, // 25: aburpos.pos.v1.ProvisioningService.StreamProvisioning:output_type -> aburpos.pos.v1.ProvisioningEvent
	14, // 26: aburpos.pos.v1.ProvisioningService.ConfirmProvisioning:output_type -> aburpos.pos.v1.ProvisioningResponse
	16, // 27: aburpos.pos.v1.NotificationService.SubscribeNotifications:output_type -> aburpos.pos.v1.Notification
	18, // 28: aburpos.pos.v1.NotificationService.AcknowledgeNotification:output_type -> aburpos.pos.v1.NotificationAckResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pos_service_proto_init() }
func file_pos_service_proto_init() {
	if File_pos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pos_service_proto_rawDesc), len(file_pos_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pos_service_proto_goTypes,
		DependencyIndexes: file_pos_service_proto_depIdxs,
		EnumInfos:         file_pos_service_proto_enumTypes,
		MessageInfos:      file_pos_service_proto_msgTypes,
	}.Build()
	File_pos_service_proto = out.File
	file_pos_service_proto_goTypes = nil
	file_pos_service_proto_depIdxs = nil
}
